// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyCZ0rMeFa3VSlIQfWG1D-FXIFoLzYcl7u4",
    appId: "1:180589732411:android:34b636409adcab6cd0f21e",
    messagingSenderId: "180589732411",
    projectId: "maddb-d0cee",
    storageBucket: "maddb-d0cee.appspot.com",
  );

 
}
